spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://39.105.29.102:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.99.100
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.99.100
    database: 0
    port: 6379
  cache:
    cache-names: menus_cache
server:
  port: 8088
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.99.100/
